apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-nginx-fpds-ingress
  labels:
    cloud.googleapis.com/location: us-east1
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: srv-nginx-fpds-ingress
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{nginx: [cnt-ui, cnt-api]}"
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: nginx-conf-secret
              readOnly: true
              mountPath: /etc/nginx/conf.d/
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 80
        - image: us-east1-docker.pkg.dev/cloudmatos-saas-demo/fpds-repo/fpds-ui:latest
          name: cnt-ui
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
              # cpu: 500m
              # memory: 256Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
        - image: us-east1-docker.pkg.dev/cloudmatos-saas-demo/fpds-repo/fpds-api:latest
          name: cnt-api
          env:
            - name: MONGO_URI
              value: ""
            - name: OPEN_API_KEY
              value: ""
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
              # cpu: 500m
              # memory: 256Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8081
      timeoutSeconds: 1800
      volumes:
        - name: nginx-conf-secret
          secret:
            secretName: nginx_config_fpds
            items:
              - key: latest
                path: default.conf